#!/bin/bash -eu

# Create flattened symbolic links in a temp directory to model shards in component directories

temp_shard_dir="/tmp/nemotron-3-super-shards"
[ -d "$temp_shard_dir" ] && rm -r "$temp_shard_dir"
mkdir -p "$temp_shard_dir"

for i in {1..20}; do
    shard_num=$(printf "%05d" $i)
    shard_file="NVIDIA-Nemotron-3-Super-120B-A12B-UD-Q4_K_M-5G-${shard_num}-of-00020.gguf"
    target_path="$temp_shard_dir/$shard_file"
    source_path="$SNAP_COMPONENTS/model-120b-a12b-q4-k-m-gguf-${i}-of-20/$shard_file"
    
    ln -s "$source_path" "$target_path"
done
