#!/bin/bash -eu

# Create symbolic links to model shreds to be found in components subdirectory in /tmp/nemotron-3-nano-shards folder.
# Create them only if they do not exist, perform a check before creating them.
SHARD_DIR="/tmp/nemotron-3-super-shards"
[ -d "$SHARD_DIR" ] && rm -r "$SHARD_DIR"
mkdir -p "$SHARD_DIR"

for i in {1..6}; do
    SHARD_NUM=$(printf "%05d" $i)
    SHARD_FILE="NVIDIA-Nemotron-3-Super-120B-A12B-UD-Q4_K_M-5G-${SHARD_NUM}-of-00020.gguf"
    TARGET_PATH="$SHARD_DIR/$SHARD_FILE"
    SOURCE_PATH="$SNAP_COMPONENTS/model-120b-a12b-q4-k-m-gguf-${i}-of-6/$SHARD_FILE"
    ln -s "$SOURCE_PATH" "$TARGET_PATH"
done
